local lp = game:getService("Players").LocalPlayer
Tool = Instance.new("Tool")
Tool.ToolTip = "Made by @benomat"
Tool.Name = "Touch"
Tool.CanBeDropped = false
Tool.RequiresHandle = true
Tool.GripForward = Vector3.new(0, 0, -1)
Tool.GripPos = Vector3.new(0, 0, .4)
Tool.GripRight = Vector3.new(1, 0, 0)
Tool.GripUp = Vector3.new(0, 1, 0)
local part = Instance.new("Part")
part.Size = Vector3.new(.8, .8, .8)
part.TopSurface = 0
part.BottomSurface = 0
part.Name = "Handle"
part.Transparency=1
part.Parent = Tool
Tool.Parent = lp.Backpack